### PR TITLE
Setup Workflow

### PR DESCRIPTION
**Pull request by siddanand**
### **Actions Performed**
- Vercel Setup (Link: https://vercel.com/docs/git/vercel-for-github)
- Added GitHub Actions on Pull Request for development deploy on Vercel. (Link: https://vercel.com/docs/git/vercel-for-github)
- Added GitHub Actions on Push to the main branch for Production on Vercel. (Link: https://vercel.com/docs/git/vercel-for-github)
- Added Preview Website on Pull Request in GitHub. (Link: https://github.com/marketplace/actions/vercel-action)
- Installed Husky for Pre-commits. (Link: https://www.npmjs.com/package/husky)
- Fixed Linting on Pre-commits and Git Actions.  (Link: https://nextjs.org/docs/basic-features/eslint)
- Added Prettier on Pre-commit.  (Link: https://prettier.io/docs/en/install.html)
- Configured Jest and Jest Coverage along with basic test cases on pre-commit and Git Actions. (Link: https://jestjs.io/docs/next/tutorial-react)
- Configured Cypress and Cypress Coverage with basic test cases on pre-commit. (Link: https://docs.cypress.io/guides/component-testing/framework-configuration#Next-js-Webpack-4)

### CODE REVIEW

**Comment by chirgjn** [comment]
Please add relevant links to help with review.

**Review by chirgjn — CHANGES_REQUESTED** [review]
- This is PR is too big for review, please break it down.
- The reference links don't seem credible, moreover I'd have to go through the videos to check the changes. Please use credible resources and document the changes if you're using videos.

**Comment by siddanand** [comment]
I have updated the reference links. I still need guidance on how to break a large pull request.

**Comment by chirgjn** [comment]
This was broken down into shorter PRs

**Pull request closed without merging**
